import { useMemo } from 'react';
import { Platform, StyleSheet, useWindowDimensions } from 'react-native';
import { ThemeColors, spacing, typography, useTheme } from '../../../support/theme/tokens';

const heroShadowStyle = Platform.select({
  web: { boxShadow: '0px 8px 16px rgba(0, 0, 0, 0.08)' } as any,
  default: {
    shadowColor: '#000000',
    shadowOpacity: 0.08,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
}) as any;

const portalShadowStyle = Platform.select({
  web: { boxShadow: '0px 6px 12px rgba(0, 0, 0, 0.06)' } as any,
  default: {
    shadowColor: '#000000',
    shadowOpacity: 0.06,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 3,
  },
}) as any;

const poemCardShadowStyle = Platform.select({
  web: { boxShadow: '0px 6px 12px rgba(0, 0, 0, 0.08)' } as any,
  default: {
    shadowColor: '#000000',
    shadowOpacity: 0.08,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 2,
  },
}) as any;

function createStyles(colors: ThemeColors, width: number) {
  const isCompact = width < 720;
  return StyleSheet.create({
  page: {
    width: '100%',
  },
  homeTopOffset: {
    ...(Platform.select({
      web: { paddingTop: 120 } as any,
      default: {},
    }) as any),
  },
  heroWrapper: {
    marginBottom: spacing.md,
  },
  heroCard: {
    backgroundColor: colors.surface,
    borderRadius: 24,
    padding: spacing.lg,
    borderWidth: 1,
    borderColor: colors.border,
    overflow: 'hidden',
    ...heroShadowStyle,
  },
  heroAtmos: {
    ...StyleSheet.absoluteFillObject,
    pointerEvents: 'none',
  },
  heroGlow: {
    position: 'absolute',
    width: 220,
    height: 220,
    borderRadius: 110,
    backgroundColor: colors.accentSoft,
    top: -120,
    right: -80,
    opacity: 0.8,
  },
  heroHalo: {
    position: 'absolute',
    width: 160,
    height: 160,
    borderRadius: 80,
    borderWidth: 1,
    borderColor: colors.border,
    bottom: -60,
    left: -20,
    opacity: 0.6,
  },
  heroBeam: {
    position: 'absolute',
    width: 200,
    height: 2,
    backgroundColor: colors.accent,
    opacity: 0.35,
    top: 70,
    left: -40,
    transform: [{ rotate: '-12deg' }],
  },
  heroKicker: {
    fontSize: typography.caption,
    fontFamily: typography.fontFamily,
    color: colors.textMuted,
    textTransform: 'uppercase',
    letterSpacing: 2,
  },
  heroTitle: {
    marginTop: spacing.xs,
    fontSize: typography.display,
    fontFamily: typography.headingFont,
    color: colors.textPrimary,
  },
  heroSubtitle: {
    marginTop: spacing.xs,
    fontSize: typography.body,
    fontFamily: typography.fontFamily,
    color: colors.textSecondary,
  },
  heroBadges: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: spacing.sm,
  },
  heroBadge: {
    backgroundColor: colors.surfaceElevated,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.border,
    paddingVertical: 4,
    paddingHorizontal: spacing.sm,
    marginRight: spacing.sm,
    marginBottom: spacing.sm,
  },
  heroBadgeText: {
    fontSize: typography.small,
    fontFamily: typography.fontFamily,
    color: colors.textSecondary,
  },
  heroActions: {
    marginTop: spacing.sm,
  },
  heroButton: {
    marginTop: spacing.sm,
  },
  primaryButton: {
    backgroundColor: colors.accent,
    paddingVertical: spacing.sm,
    borderRadius: 999,
    alignItems: 'center',
  },
  primaryButtonText: {
    fontSize: typography.caption,
    fontFamily: typography.fontFamily,
    color: colors.textPrimary,
  },
  secondaryButton: {
    marginTop: spacing.sm,
    borderWidth: 1,
    borderColor: colors.border,
    paddingVertical: spacing.sm,
    borderRadius: 999,
    alignItems: 'center',
    backgroundColor: colors.surface,
  },
  secondaryButtonText: {
    fontSize: typography.caption,
    fontFamily: typography.fontFamily,
    color: colors.textSecondary,
  },
  highlightRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: spacing.md,
  },
  highlightCard: {
    flexGrow: 1,
    minWidth: isCompact ? '100%' : 150,
    backgroundColor: colors.surface,
    borderRadius: 18,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
    marginRight: isCompact ? 0 : spacing.sm,
    marginBottom: spacing.sm,
  },
  highlightTitle: {
    fontSize: typography.body,
    fontFamily: typography.headingFont,
    color: colors.textPrimary,
    marginBottom: spacing.xs,
  },
  highlightText: {
    fontSize: typography.caption,
    fontFamily: typography.fontFamily,
    color: colors.textMuted,
  },
  journeyRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  journeyCard: {
    flexGrow: 1,
    minWidth: isCompact ? '100%' : 160,
    backgroundColor: colors.surface,
    borderRadius: 18,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
    marginRight: isCompact ? 0 : spacing.sm,
    marginBottom: spacing.sm,
  },
  journeyIndex: {
    fontSize: typography.small,
    fontFamily: typography.fontFamily,
    color: colors.textMuted,
    letterSpacing: 1,
    marginBottom: spacing.xs,
  },
  journeyTitle: {
    fontSize: typography.body,
    fontFamily: typography.headingFont,
    color: colors.textPrimary,
    marginBottom: spacing.xs,
  },
  journeyText: {
    fontSize: typography.caption,
    fontFamily: typography.fontFamily,
    color: colors.textSecondary,
  },
  discoverGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  discoverCard: {
    width: isCompact ? '100%' : '47%',
    backgroundColor: colors.surface,
    borderRadius: 18,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
    marginRight: isCompact ? 0 : spacing.sm,
    marginBottom: spacing.sm,
    ...heroShadowStyle,
  },
  discoverTitle: {
    fontSize: typography.body,
    fontFamily: typography.headingFont,
    color: colors.textPrimary,
    marginBottom: spacing.xs,
  },
  discoverText: {
    fontSize: typography.caption,
    fontFamily: typography.fontFamily,
    color: colors.textSecondary,
    marginBottom: spacing.sm,
  },
  discoverButton: {
    alignSelf: 'flex-start',
  },
  section: {
    marginBottom: spacing.lg,
  },
  sectionHeader: {
    marginBottom: spacing.sm,
  },
  sectionTitle: {
    fontSize: typography.title,
    fontFamily: typography.headingFont,
    color: colors.textPrimary,
  },
  sectionHint: {
    marginTop: spacing.xs,
    fontSize: typography.caption,
    fontFamily: typography.fontFamily,
    color: colors.textSecondary,
  },
  sectionAction: {
    marginTop: spacing.xs,
    alignSelf: 'flex-start',
  },
  sectionActionText: {
    fontSize: typography.caption,
    fontFamily: typography.fontFamily,
    color: colors.textSecondary,
  },
  loreGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  loreCard: {
    width: isCompact ? '100%' : '47%',
    backgroundColor: colors.surface,
    borderRadius: 18,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
    marginRight: isCompact ? 0 : spacing.sm,
    marginBottom: spacing.sm,
  },
  loreTag: {
    alignSelf: 'flex-start',
    paddingVertical: 2,
    paddingHorizontal: spacing.sm,
    borderRadius: 999,
    backgroundColor: colors.surfaceMuted,
    marginBottom: spacing.sm,
  },
  loreTagText: {
    fontSize: typography.small,
    fontFamily: typography.fontFamily,
    color: colors.textMuted,
  },
  loreTitle: {
    fontSize: typography.body,
    fontFamily: typography.headingFont,
    color: colors.textPrimary,
    marginBottom: spacing.xs,
  },
  loreText: {
    fontSize: typography.caption,
    fontFamily: typography.fontFamily,
    color: colors.textSecondary,
  },
  loreButton: {
    marginTop: spacing.sm,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
    alignSelf: 'flex-start',
  },
  ritualCard: {
    backgroundColor: colors.surfaceMuted,
    borderRadius: 20,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
  },
  ritualPrompt: {
    fontSize: typography.body,
    fontFamily: typography.fontFamily,
    color: colors.textPrimary,
  },
  ritualHint: {
    marginTop: spacing.xs,
    fontSize: typography.caption,
    fontFamily: typography.fontFamily,
    color: colors.textSecondary,
  },
  moodGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  moodPill: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    paddingVertical: 6,
    paddingHorizontal: spacing.sm,
    marginRight: isCompact ? spacing.xs : spacing.sm,
    marginBottom: spacing.sm,
  },
  moodPillHalf: {
    width: '47%',
    marginRight: spacing.xs,
  },
  moodPillActive: {
    borderColor: colors.accent,
    backgroundColor: colors.accentSoft,
  },
  moodDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginRight: spacing.xs,
  },
  moodLabel: {
    fontSize: typography.caption,
    fontFamily: typography.fontFamily,
    color: colors.textSecondary,
  },
  moodLabelActive: {
    color: colors.textPrimary,
  },
  moodDescriptionCard: {
    marginTop: spacing.sm,
    backgroundColor: colors.surfaceMuted,
    borderRadius: 18,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
  },
  moodDescriptionTitle: {
    fontSize: typography.body,
    fontFamily: typography.headingFont,
    color: colors.textPrimary,
    marginBottom: spacing.xs,
  },
  moodDescriptionText: {
    fontSize: typography.caption,
    fontFamily: typography.fontFamily,
    color: colors.textSecondary,
  },
  symbolGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  symbolCard: {
    width: isCompact ? '100%' : '47%',
    backgroundColor: colors.surface,
    borderRadius: 18,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
    marginRight: isCompact ? 0 : spacing.sm,
    marginBottom: spacing.sm,
  },
  symbolLabel: {
    marginTop: spacing.sm,
    fontSize: typography.caption,
    fontFamily: typography.fontFamily,
    color: colors.textSecondary,
  },
  symbolWings: {
    width: 24,
    height: 10,
    borderWidth: 1,
    borderRadius: 6,
  },
  symbolHalo: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 1,
  },
  symbolHorizon: {
    width: 24,
    height: 2,
    borderRadius: 2,
  },
  symbolWhirl: {
    width: 16,
    height: 16,
    borderWidth: 1,
    borderRadius: 8,
  },
  symbolMeteor: {
    width: 24,
    height: 12,
  },
  symbolMeteorTrail: {
    position: 'absolute',
    width: 16,
    height: 2,
    borderRadius: 2,
    top: 5,
    left: 0,
  },
  symbolMeteorCore: {
    position: 'absolute',
    width: 6,
    height: 6,
    borderRadius: 3,
    top: 3,
    right: 0,
  },
  filterRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: spacing.md,
  },
  filterChip: {
    paddingVertical: spacing.xs,
    paddingHorizontal: spacing.sm,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    marginRight: spacing.sm,
    marginBottom: spacing.sm,
  },
  filterChipActive: {
    borderColor: colors.accent,
    backgroundColor: colors.accentSoft,
  },
  filterChipPressed: {
    opacity: 0.75,
  },
  filterChipText: {
    fontSize: typography.caption,
    color: colors.textSecondary,
    fontFamily: typography.fontFamily,
  },
  filterChipTextActive: {
    color: colors.textPrimary,
  },
  poemList: {
    paddingBottom: spacing.lg,
  },
  poemSeparator: {
    marginTop: spacing.md,
  },
  poemCard: {
    backgroundColor: colors.surface,
    borderRadius: 20,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
    ...poemCardShadowStyle,
  },
  poemHeader: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  poemTitle: {
    flex: 1,
    fontSize: typography.body,
    fontFamily: typography.fontFamily,
    color: colors.textPrimary,
    marginRight: spacing.sm,
  },
  poemMoodBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 4,
    paddingHorizontal: spacing.sm,
    borderRadius: 999,
    borderWidth: 1,
    backgroundColor: colors.surfaceElevated,
  },
  poemMoodDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginRight: spacing.xs,
  },
  poemMoodLabel: {
    fontSize: typography.small,
    fontFamily: typography.fontFamily,
    color: colors.textPrimary,
  },
  poemAuthor: {
    marginTop: spacing.xs,
    fontSize: typography.caption,
    fontFamily: typography.fontFamily,
    color: colors.textSecondary,
  },
  poemMetaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: spacing.xs,
  },
  poemMeta: {
    fontSize: typography.small,
    fontFamily: typography.fontFamily,
    color: colors.textMuted,
    marginRight: spacing.sm,
    marginTop: spacing.xs,
  },
  badgeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: spacing.sm,
  },
  badge: {
    paddingVertical: 4,
    paddingHorizontal: spacing.sm,
    borderRadius: 999,
    backgroundColor: colors.surfaceMuted,
    marginRight: spacing.sm,
    marginBottom: spacing.xs,
  },
  badgeText: {
    fontSize: typography.small,
    fontFamily: typography.fontFamily,
    color: colors.textSecondary,
  },
  centered: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: spacing.lg,
  },
  loadingText: {
    marginTop: spacing.sm,
    fontFamily: typography.fontFamily,
    color: colors.textMuted,
  },
  errorBox: {
    backgroundColor: colors.surface,
    borderRadius: 16,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: spacing.lg,
  },
  errorText: {
    color: colors.danger,
    fontFamily: typography.fontFamily,
    marginBottom: spacing.sm,
  },
  retryButton: {
    alignSelf: 'flex-start',
    paddingVertical: spacing.xs,
    paddingHorizontal: spacing.sm,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.border,
  },
  retryText: {
    color: colors.textPrimary,
    fontSize: typography.caption,
    fontFamily: typography.fontFamily,
  },
  emptyState: {
    alignItems: 'center',
    paddingVertical: spacing.xxl,
  },
  emptyTitle: {
    fontSize: typography.body,
    fontFamily: typography.fontFamily,
    color: colors.textPrimary,
    marginBottom: spacing.xs,
  },
  emptyText: {
    fontSize: typography.caption,
    fontFamily: typography.fontFamily,
    color: colors.textMuted,
    textAlign: 'center',
    marginBottom: spacing.md,
  },
  emptyButton: {
    backgroundColor: colors.accent,
    paddingVertical: spacing.xs,
    paddingHorizontal: spacing.lg,
    borderRadius: 999,
  },
  emptyButtonText: {
    color: colors.textPrimary,
    fontSize: typography.caption,
    fontFamily: typography.fontFamily,
  },
  portalCard: {
    backgroundColor: colors.surface,
    borderRadius: 24,
    padding: spacing.lg,
    borderWidth: 1,
    borderColor: colors.border,
    ...portalShadowStyle,
  },
  portalTitle: {
    fontSize: typography.title,
    fontFamily: typography.headingFont,
    color: colors.textPrimary,
  },
  portalText: {
    marginTop: spacing.xs,
    fontSize: typography.body,
    fontFamily: typography.fontFamily,
    color: colors.textSecondary,
    marginBottom: spacing.md,
  },
  });
}

export function useStyles() {
  const { theme } = useTheme();
  const { width } = useWindowDimensions();
  return useMemo(() => createStyles(theme.colors, width), [theme.colors, width]);
}
