<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251208134414 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE author (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, pseudo VARCHAR(100) NOT NULL, email VARCHAR(180) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, mood_color VARCHAR(255) NOT NULL, totem_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_BDAFD8C8E7927C74 ON author (email)');
        $this->addSql('CREATE INDEX IDX_BDAFD8C8A1EBF819 ON author (totem_id)');
        $this->addSql('CREATE TABLE author_reward (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, earned_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, author_id INT NOT NULL, reward_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_AB12447EF675F31B ON author_reward (author_id)');
        $this->addSql('CREATE INDEX IDX_AB12447EE466ACA1 ON author_reward (reward_id)');
        $this->addSql('CREATE TABLE feather_vote (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, feather_type VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, poem_id INT NOT NULL, voter_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_532EBE8E8938791B ON feather_vote (poem_id)');
        $this->addSql('CREATE INDEX IDX_532EBE8EEBB4B8AD ON feather_vote (voter_id)');
        $this->addSql('CREATE TABLE poem (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(255) NOT NULL, mood_color VARCHAR(255) NOT NULL, title VARCHAR(255) NOT NULL, content TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, published_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, author_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2279719AF675F31B ON poem (author_id)');
        $this->addSql('CREATE TABLE reward (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(100) NOT NULL, label VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4ED1725377153098 ON reward (code)');
        $this->addSql('CREATE TABLE totem (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(120) NOT NULL, description TEXT DEFAULT NULL, picture VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE users (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E9E7927C74 ON users (email)');
        $this->addSql('ALTER TABLE author ADD CONSTRAINT FK_BDAFD8C8A1EBF819 FOREIGN KEY (totem_id) REFERENCES totem (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE author_reward ADD CONSTRAINT FK_AB12447EF675F31B FOREIGN KEY (author_id) REFERENCES author (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE author_reward ADD CONSTRAINT FK_AB12447EE466ACA1 FOREIGN KEY (reward_id) REFERENCES reward (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE feather_vote ADD CONSTRAINT FK_532EBE8E8938791B FOREIGN KEY (poem_id) REFERENCES poem (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE feather_vote ADD CONSTRAINT FK_532EBE8EEBB4B8AD FOREIGN KEY (voter_id) REFERENCES author (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE poem ADD CONSTRAINT FK_2279719AF675F31B FOREIGN KEY (author_id) REFERENCES author (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE author DROP CONSTRAINT FK_BDAFD8C8A1EBF819');
        $this->addSql('ALTER TABLE author_reward DROP CONSTRAINT FK_AB12447EF675F31B');
        $this->addSql('ALTER TABLE author_reward DROP CONSTRAINT FK_AB12447EE466ACA1');
        $this->addSql('ALTER TABLE feather_vote DROP CONSTRAINT FK_532EBE8E8938791B');
        $this->addSql('ALTER TABLE feather_vote DROP CONSTRAINT FK_532EBE8EEBB4B8AD');
        $this->addSql('ALTER TABLE poem DROP CONSTRAINT FK_2279719AF675F31B');
        $this->addSql('DROP TABLE author');
        $this->addSql('DROP TABLE author_reward');
        $this->addSql('DROP TABLE feather_vote');
        $this->addSql('DROP TABLE poem');
        $this->addSql('DROP TABLE reward');
        $this->addSql('DROP TABLE totem');
        $this->addSql('DROP TABLE users');
    }
}
